enum RequestType {
  CONNECTION = "Connection",
  CREDENTIAL = "Credential",
}

enum ToastMsgType {
  COPIED_TO_CLIPBOARD = "copiedToClipboard",
  IDENTIFIER_REQUESTED = "identifierRequested",
  IDENTIFIER_CREATED = "identifierCreated",
  GROUP_REQUEST_SEND = "grouprequestsend",
  UNABLE_CREATE_GROUP_ERROR = "unablecreategrouperror",
  DELEGATED_IDENTIFIER_CREATED = "delegatedidentifiercreated",
  IDENTIFIER_UPDATED = "identifierUpdated",
  IDENTIFIER_NAME_UPDATED = "identifierNameUpdated",
  IDENTIFIER_USERNAME_UPDATED = "identifierUsernameUpdated",
  GROUP_UPDATED = "groupnameupdate",
  GROUP_UPDATED_FAIL = "groupnameupdateerror",
  IDENTIFIER_DELETED = "identifierDeleted",
  CREDENTIAL_DELETED = "credentialDeleted",
  CREDENTIAL_RESTORED = "credentialRestored",
  CREDENTIALS_DELETED = "credentialsDeleted",
  CREDENTIALS_RESTORED = "credentialsRestored",
  CREDENTIAL_ARCHIVED = "credentialArchived",
  CONNECTION_DELETED = "connectionDeleted",
  CONNECTION_REQUEST_PENDING = "connectionRequestPending",
  CONNECTION_REQUEST_INCOMING = "connectionRequestIncoming",
  NEW_CONNECTION_ADDED = "newConnectionAdded",
  CREDENTIAL_REQUEST_PENDING = "credentialRequestPending",
  NEW_CREDENTIAL_ADDED = "newCredentialAdded",
  NOTES_UPDATED = "notesUpdated",
  NOTE_REMOVED = "noteRemoved",
  MAX_FAVOURITES_REACHED = "maxFavouritesReachedError",
  WALLET_CONNECTION_DELETED = "dappconnectiondeleted",
  WALLET_CONNECTION_DELETE_ERROR = "dappconnectiondeleteerror",
  CONNECT_WALLET_SUCCESS = "connectwalletsuccess",
  DISCONNECT_WALLET_SUCCESS = "disconnectwallet",
  UNABLE_CONNECT_WALLET = "unableconnectwalleterror",
  PEER_ID_SUCCESS = "peeridsuccess",
  PEER_ID_ERROR = "peeriderror",
  SETUP_BIOMETRIC_AUTHENTICATION_SUCCESS = "setupbiometricsuccess",
  ROTATE_KEY_SUCCESS = "rotatekeysuccess",
  ROTATE_KEY_ERROR = "rotatekeyerror",
  SCAN_SELF_CONNECTION = "scanselfconnectionerror",
  CONNECTION_ERROR = "connectionerror",
  NEW_MULTI_SIGN_MEMBER = "newmultisignmember",
  PASSCODE_UPDATED = "passcodeupdated",
  PASSWORD_UPDATED = "passwordupdated",
  PASSWORD_SETTING_UPDATE = "passwordsettingupdate",
  PASSWORD_SETTING_UPDATE_FAIL = "passwordsettingupdateerror",
  PASSWORD_CREATED = "passwordcreated",
  PROPOSED_CRED_SUCCESS = "proposedcredsuccess",
  SHARE_CRED_SUCCESS = "sharecredsuccess",
  SHARE_CRED_FAIL = "sharecrederror",
  PROPOSAL_CRED_ACCEPTED = "proposalcredaccepted",
  PROPOSAL_CRED_REJECT = "proposalcredreject",
  PROPOSAL_CRED_FAIL = "proposalcredfailerror",
  DELETE_CONNECTION_FAIL = "deleteconnectionerror",
  DELETE_CRED_FAIL = "deletecrederror",
  DELETE_IDENTIFIER_FAIL = "deleteidentifiererror",
  ARCHIVED_CRED_FAIL = "archivedcrederror",
  SIGN_SUCCESSFUL = "signsuccessful",
  UNABLE_DELETE_PASSWORD_HINT = "deletepasswordhinterror",
  UNABLE_EDIT_IDENTIFIER = "editidentifiererror",
  FAILED_UPDATE_CONNECTION = "failedupdateconnectionerror",
  DUPLICATE_CONNECTION = "duplicateconnectionerror",
  GROUP_ID_NOT_MATCH_ERROR = "groupidnotmatcherror",
  DELETE_ACCOUNT_ERROR = "deleteaccounterror",
  DELETE_ACCOUNT_SUCCESS = "deleteaccountsuccess",
  REMOTE_SIGN_SUCCESS = "remotesignsuccess",
  UNKNOWN_ERROR = "unknownerror",
  URL_ERROR = "urlerror",
  PROFILE_SWITCHED = "profileswitched",
  UNABLE_TO_SWITCH_PROFILE = "unabletoswitchprofile",
  NOT_VALID_GROUP_INVITE = "notvalidgrouperror",
  GROUP_NAME_NOT_FOUND_ERROR = "groupnamenotfounderror",
  DUPLICATE_GROUP_ID_ERROR = "duplicategroupiderror",
  GROUP_METADATA_NOT_FOUND_ERROR = "groupmetadatanotfounderror",
  UNABLE_TO_ACCEPT = "unabletoaccepterror",
  ACCEPT_SUCCESS = "acceptsuccess",
  CONNECT_URL_MISMATCH = "connecturlmismatch",
  INVALID_BOOT_URL = "invalidbooturlerror",
  MISMATCH_ERROR = "mismatcherror",
  INVALID_REMOVED_CONNECTION_URL = "invalidremovedconnectionurlerror",
  NETWORK_ERROR = "networkerror",
  CREATE_IDENTIFIER_FAIL = "createidentifiererror",
  INVALID_CONNECTION_URL = "invalidconnectionurlerror",
  PROFILE_NOT_EXIST = "profilenotexisterror",
  MEMBER_ALREADY_EXIST = "memberalreadyexisterror",
  GROUP_CREATED = "groupcreated",
  SIGN_ERROR = "signerror",
}

const PASSCODE_MAPPING = {
  numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0],
  labels: [
    [""],
    ["A B C"],
    ["D E F"],
    ["G H I"],
    ["J K L"],
    ["M N O"],
    ["P Q R S"],
    ["T U V"],
    ["W X Y Z"],
    [""],
  ],
};

enum BackEventPriorityType {
  LockPage = 1001,
  Alert = 1000,
  Modal = 500,
  Scanner = 103,
  Page = 102,
  Tab = 101,
}

export { BackEventPriorityType, PASSCODE_MAPPING, RequestType, ToastMsgType };
